package com.bawei.pss20191204.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.pss20191204.bean.LawyerData;

import com.bawei.pss20191204.dao.LawyerDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lawyerDataDaoConfig;

    private final LawyerDataDao lawyerDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lawyerDataDaoConfig = daoConfigMap.get(LawyerDataDao.class).clone();
        lawyerDataDaoConfig.initIdentityScope(type);

        lawyerDataDao = new LawyerDataDao(lawyerDataDaoConfig, this);

        registerDao(LawyerData.class, lawyerDataDao);
    }
    
    public void clear() {
        lawyerDataDaoConfig.clearIdentityScope();
    }

    public LawyerDataDao getLawyerDataDao() {
        return lawyerDataDao;
    }

}
